name: Build and publish

on:
  workflow_dispatch

jobs:
  build_pages:
    name: Publish as GitHub Pages Website
    runs-on: ubuntu-latest
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4

    - name: Set up Java 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '11'

    - name: Install Ant + Ant-Contrib
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends ant ant-contrib

    - name: Prepare Data
      run: |
        ant -f ./build.xml

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
